### ISSUE TITLE
[Bug]: Game lags a lot when EMI is rendering wooden buckets

### ISSUE THREAD

**Issue by truskawex** [cech12/WoodenBucket#19]
### Minecraft Version

1.19.2

### Mod Loader

Forge

### Mod Loader Version

43.4.0

### Mod Version

1.19-1.1.0.0

### Modpack or other Mod

I'm playing Star Technology Beta 10 Hotfix 4 (31.05.2024)
https://www.curseforge.com/minecraft/modpacks/star-technology

### Describe the Issue

When searching in EMI, the game starts to lag(a lot) as soon as the wooden buckets appear as the result (only when huge quantity of them is visible)

![2024-06-23_17 06 49](https://github.com/cech12/WoodenBucket/assets/27358918/e117b9e0-f7d6-4c5b-9b49-6b1dbf722de5)
 

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Nothing more than in modpack

**Comment by cech12** [comment]
Thanks for your report! I will look into that when I have time :)

**Comment by cech12** [comment]
@truskawex This issue was fixed in the BucketLib mod in the following versions:

* 1.19.2-1.0.8.1
* 1.19.4-1.3.1.1
* 1.20.1-2.3.4.1
* 1.20.4-3.2.1.2
* 1.20.6-3.3.0.6
* 1.21-4.0.0.3

Please test the fitting version and let me know if it is fixed in your environment. :)

**Comment by truskawex** [comment]
Works much better now!
