### ISSUE TITLE
[Bug]: Can't pickup Modded Fluid from Dehydration Mod

### ISSUE THREAD

**Issue by CJDevZ** [cech12/WoodenBucket#20]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Mod Version

4.0.0.0

### Modpack or other Mod

It's related to the Mod [Dehydration](https://modrinth.com/mod/dehydration)

### Describe the Issue

I've placed Purified Water and then tried to pick it up with a Wooden Bucket.
The Fluid disappeared, the bucket wasn't filled

**Comment by cech12** [comment]
Thanks for your report! I will look into that when I have time :)

**Comment by cech12** [comment]
The main issue seems to be in the Dehydration mod: https://github.com/Globox1997/Dehydration/issues/168

But the disappearence should be fixed on my side as well. :)

**Comment by cech12** [comment]
Fixed the disappearing in BucketLib 1.21-4.0.0.4. But the fluid is still not compatible. I leave this issue open until Dehydration fixed the bucket item to be compatible.

**Comment by cech12** [comment]
Fixed with the release of Dehydration 1.3.7
