### ISSUE TITLE
[Bug]: Possible Conflict with Dynamic Trees

### ISSUE THREAD

**Issue by whatebbs** [cech12/WoodenBucket#22]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Mod Loader Version

Forge 47.3.0

### Mod Version

1.20.1-2.1.0.0

### Modpack or other Mod

Many mods, but Dynamic Trees was the one that reacted to Wooden Bucket's addition.

### Describe the Issue

Loaded the mods.
Ran the game.
Failed to make it to Main Menu.
In-game error logged claimed that Dynamic Trees failed to find a resource.
Wooden Bucket must be the issue because everything else worked fine right before I added it, and after I removed it.

### Logs

https://pastebin.com/UAUwVkRQ

### Do you use any performance-enhancing mods (e.g. OptiFine)?

I use Embeddium, Oculus and various mods to improve lag and framerate

**Comment by cech12** [comment]
@whatebbs Hey, why are you opening a Dynamic Tree issue here on the Wooden Bucket Github page? What is the relation to my mod?

**Comment by whatebbs** [comment]
> @whatebbs Hey, why are you opening a Dynamic Tree issue here on the Wooden Bucket Github page? What is the relation to my mod?

When I installed the wooden bucket mod and it's requirement, an error popped up having to with Dynamic Trees. I know Dynamic Trees worked before without it, so I think the two are in conflict with each other and wooden bucket is the problem.

**Comment by cech12** [comment]
Sorry, but I cannot reproduce your issue. I can launch the game, see the main menu, start a game, can see trees of DynamicTrees mod and can equip a wooden bucket.

![Image](https://github.com/user-attachments/assets/b7702f29-8aa2-4e38-bb59-38f526cfd3f3)

Environment:
- PrismLauncher 8.3
- Minecraft 1.20.1
- Forge 47.3.0

Following mods are installed for reproduction:
- BucketLib 1.20.1-2.3.4.1
- Dynamic Trees 1.20.1-1.3.0-BETA11
- Embeddium 0.3.25+mc1.20.1
- Oculus 1.20.1-1.7.0
- Wooden Bucket 1.20.1-2.1.0.0

@whatebbs Please try to find out, which of your other mods is causing the incompatibility, or give some more information about your environment, if it is different from mine.

**Comment by whatebbs** [comment]
> Sorry, but I cannot reproduce your issue. I can launch the game, see the main menu, start a game, can see trees of DynamicTrees mod and can equip a wooden bucket.
> 
> ![Image](https://private-user-images.githubusercontent.com/16005054/351005654-b7702f29-8aa2-4e38-bb59-38f526cfd3f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzIyMzMsIm5iZiI6MTcyMTY3MTkzMywicGF0aCI6Ii8xNjAwNTA1NC8zNTEwMDU2NTQtYjc3MDJmMjktOGFhMi00ZTM4LWJiNTktMzhmNTI2Y2ZkM2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDE4MTIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlOTZjMGE0OGYzMTU1M2UxZDFjZDgzZWZhMzAxNGQ3ZDRiMzU0YmEwMjgxYzdhMjQ2NDA0OTY1OTY0MTlkZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HtlUnvoLZEU5hAgS6BYfKIlTEz9PlFFoRlspHvW7mQI)
> 
> Environment:
> 
>     * PrismLauncher 8.3
> 
>     * Minecraft 1.20.1
> 
>     * Forge 47.3.0
> 
> 
> Following mods are installed for reproduction:
> 
>     * BucketLib 1.20.1-2.3.4.1
> 
>     * Dynamic Trees 1.20.1-1.3.0-BETA11
> 
>     * Embeddium 0.3.25+mc1.20.1
> 
>     * Oculus 1.20.1-1.7.0
> 
>     * Wooden Bucket 1.20.1-2.1.0.0
> 
> 
> @whatebbs Please try to find out, which of your other mods is causing the incompatibility, or give some more information about your environment, if it is different from mine.

After playing again with newly installed RAM (went from a mere 3G that came with the PC to 16G), the problem went away. So far, I've had no further issues. Maybe the RAM ran out before Dynamic Trees could find its resource file or something. Thank you for ensuring there really was no problem with mod incompatibility. The issue seems gone for now.

**Comment by cech12** [comment]
Thanks for your feedback! Nice to see that Everthing works now :) Feel free to open another issue if you find a bug :)
