### ISSUE TITLE
[Bug]: Any bucket with water in the title evaporates in the nether 

### ISSUE THREAD

**Issue by benbenlaw** [cech12/WoodenBucket#7]
### Minecraft Version

1.19.2

### Forge Version

43.2.0

### Mod Version

1.1.0.0

### Describe the Issue

any wooden bucket with water in the name evaporates even though they can be placed with iron buckets

**Comment by cech12** [comment]
Is there a mod installed or a game config changed to let water be placeable in the Nether?

**Comment by benbenlaw** [comment]
nope its custom fluids made with kubjes

**Comment by cech12** [comment]
Thanks for your response, i will look into this when i have time :)

**Comment by cech12** [comment]
@benbenlaw Could you send me the KubeJS script of the fluids you have added?
I think this is a KubeJS or Archiceture issue, because I cannot find a way to define the vaporize behaviour of a fluid type which is generated there. But I could test around with the script :)

**Comment by cech12** [comment]
My mod uses the Forge [`FluidUtils::tryPlaceFluid`](https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/src/main/java/net/minecraftforge/fluids/FluidUtil.java#L574) method to place fluids, where the vaporize behaviour of the fluid type is used to decide if the fluid should vaporize or not. The default behaviour is to get the FluidBlockState and check if its material is `Material.WATER`: https://github.com/MinecraftForge/MinecraftForge/blob/ae954bea17f43ba8ab6baa83b760a4817e748a5d/src/main/java/net/minecraftforge/fluids/FluidType.java#L824

I cannot find a possibility to define a FluidBlock Material or a vaporize behaviour in KubeJS or Architectury.

To fix this issue, I need to find out if:
- the used BucketItem of KubeJS/Architectury/Forge acts different to the `FluidUtil::tryPlaceFluid` method
- KubeJS/Architectury has an issue to define vaporize behaviour
- (or both)

**Comment by benbenlaw** [comment]
StartupEvents.registry('fluid', event => {
	event.create('cryptopolis:cleansing_water').thinTexture(0x0066ff).bucketColor(0x0066ff).displayName('Cleansing Water')
})

**Comment by benbenlaw** [comment]
i wonder then if theres something in kubejs to define the fluid material

**Comment by cech12** [comment]
Thanks for the script! :) When I have tiime, I will look deeper into this issue. :)

Yes this is one part of the issue^^

**Comment by benbenlaw** [comment]
thanks very much :)

**Comment by cech12** [comment]
I opened an issue for Forge. I hope, we can find a solution for this. :)

**Comment by cech12** [comment]
I opened a PR: https://github.com/MinecraftForge/MinecraftForge/pull/9269

**Comment by cech12** [comment]
The 1.19.3 PR was merged to MinecraftForge. I opened additional PRs for:
- 1.19.2 https://github.com/MinecraftForge/MinecraftForge/pull/9340
- 1.18.2 https://github.com/MinecraftForge/MinecraftForge/pull/9341

This issue is fixed by https://github.com/MinecraftForge/MinecraftForge/pull/9340. It is likely that the fluids of KubeJS will vaporize in the Nether even if they are placed by the "vanilla" bucket. An issue for KubeJS would be a good idea to fix that^^

**Comment by cech12** [comment]
@benbenlaw This issue should be fixed since Forge 43.2.6. Every other resulting issue should be tracked in another Github issue linked in the comments or in new issues. :)
